### PR TITLE
Added heartbeat timeout option to Run

### LINKED ISSUE #494: Addition of option for no heartbeat when making server requests

### PR DESCRIPTION
**Pull request by kzscisoft**
Adds the `timeout` argument to `Run.init` to specify the timeout period for the run where setting it to `None` disables the timeout.

Closes #494

### CODE REVIEW

**Comment by james-panayis** [comment]
Would be nice if there was a test that tried the case where the timeout is set to `None` (and ideally then waited over 180 seconds to confirm that the run doesn't end up in the lost state).

**Comment by kzscisoft** [comment]
@james-panayis The issue with that is it will be a significant extension to CI execution time

**Comment by james-panayis** [comment]
@kzscisoft if you did the wait then sure, that'd increase the CI time. But just confirming that a run can actually be created with timeout `None` would not take especially long. I mostly would just like a test to confirm that the server will correctly interpret the request as an instruction to create a run.

**Comment by kzscisoft** [comment]
@james-panayis good point, the validation was not allowing `None`! So this test picked that up. Added it in now 🙂

**Pull request merged**
